### ISSUE TITLE
Add emergency contact details to users table

### ISSUE THREAD

**Issue by taterhead247** [F3-Nation/F3-Data-Models#1]
Would it be possible to add `emergency_contact_number` and `emergency_contact_notes` fields to the `users` table? I imagine a phone number in the number field. I want to separate that out specifically so it can be clickable in our apps. But then the notes field can be for the person's name, details, and any medical facts they want to add.

**Comment by evanpetzoldt** [comment]
Yep, we can do that. BTW, the thought behind the `meta` column is as a catch all, either for custom things regions want to track or anytime we don't feel like a new field requires a full column.

Btw, this reminds me... I need a slash command or something that could bring this info up.

**Comment by evanpetzoldt** [comment]
Included in v0.1.7
