### ISSUE TITLE
Add field for log channel ID

### ISSUE THREAD

**Issue by taterhead247** [F3-Nation/F3-Data-Models#2]
Now that we have everything in one app, we can uniformly set which channel log messages to be posted to in the app. For that would need to add something like `log_channel_id` to the `slack_spaces` table.

**Comment by evanpetzoldt** [comment]
I'm stuffing all Slack bot settings into the `app_settings` json column, so that's where this would live

**Comment by evanpetzoldt** [comment]
Closing as no further action needed
