### ISSUE TITLE
orgs_x_slack name and foreign key

### ISSUE THREAD

**Issue by taterhead247** [F3-Nation/F3-Data-Models#3]
Should the name of table `orgs_x_slack` actually be `orgs_x_slack`? And should the `slack_id` field have a foreign key to the `slack_spaces` table? Should the field be called `slack_spaces_id` to eliminate confusion between `slack_spaces` and `slack_users` tables?

**Comment by evanpetzoldt** [comment]
Are you suggesting `orgs_x_slack_spaces`? That would be more consistent with the other tables. And I think I already made the name changes you are suggesting
